apiVersion: v1
data:
  example_config.json: |-
    [
      {
        "name": "counter_increase_steady",
        "metric_type": "counter",
        "pattern": "increasing",
        "base_value": 100,
        "amplitude": 5,
        "frequency": 1.0,
        "noise_level": 0.0
      },
      {
        "name": "counter_breach_threshold",
        "metric_type": "counter",
        "pattern": "threshold_breach",
        "base_value": 50,
        "amplitude": 25,
        "frequency": 1.0,
        "noise_level": 0.0
      },
      {
        "name": "gauge_sine",
        "metric_type": "gauge",
        "pattern": "sine_wave",
        "base_value": 50,
        "amplitude": 30,
        "frequency": 0.1,
        "noise_level": 0.0
      },
      {
        "name": "counter_sawtooth",
        "metric_type": "counter",
        "pattern": "sawtooth",
        "base_value": 200,
        "amplitude": 100,
        "frequency": 1.0,
        "noise_level": 0.0
      }
    ]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metrics-generator-config
  namespace: test-metrics
