apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-generator
  namespace: test-metrics
  labels:
    app: metrics-generator
    monitoring: prometheus
    release: prom-operator
spec:
  selector:
    matchLabels:
      app: metrics-generator
      monitoring: prometheus
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 60s
    scrapeTimeout: 10s
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: '(test_metrics_.*)'
      action: keep
  namespaceSelector:
    matchNames:
    - test-metrics